apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "helm-jenkins-application.fullname" . }}
  labels:
    app: {{ include "helm-jenkins-application.name" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "helm-jenkins-application.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "helm-jenkins-application.name" . }}
    spec:
      containers:
        - name: jenkins
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: jenkins-data
              mountPath: /var/jenkins_home
      volumes:
        - name: jenkins-data
          emptyDir: {}
