apiVersion: v1
kind: Service
metadata:
  name: {{ include "helm-jenkins-application.fullname" . }}
  labels:
    app: {{ include "helm-jenkins-application.name" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8080
      protocol: TCP
      name: http
      {{- if eq .Values.service.type "NodePort" }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
  selector:
    app: {{ include "helm-jenkins-application.name" . }}
