apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "helm-consumer-application.fullname" . }}
  labels:
    {{- include "helm-consumer-application.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "helm-consumer-application.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "helm-consumer-application.labels" . | nindent 8 }}
    spec:
      containers:
        - name: consumer
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: RABBITMQ_DEFAULT_USER
              valueFrom:
                secretKeyRef:
                  name: {{ include "helm-consumer-application.fullname" . }}
                  key: username
            - name: RABBITMQ_DEFAULT_PASS
              valueFrom:
                secretKeyRef:
                  name: {{ include "helm-consumer-application.fullname" . }}
                  key: password
          command: ["python", "app.py"]
          args:
            - "-p"
            - "{{ .Values.rabbitmq.port }}"
            - "-s"
            - "{{ .Values.rabbitmq.host }}"
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      nodeSelector:
        {{- toYaml .Values.nodeSelector | nindent 8 }}
      tolerations:
        {{- toYaml .Values.tolerations | nindent 8 }}
      affinity:
        {{- toYaml .Values.affinity | nindent 8 }}
