apiVersion: v1
kind: Secret
metadata:
  name: {{ include "helm-rabbitmq-application.fullname" . }}
  labels:
    {{- include "helm-rabbitmq-application.labels" . | nindent 4 }}
type: Opaque
data:
  username: {{ .Values.rabbitmq.username | b64enc }}
  password: {{ .Values.rabbitmq.password | b64enc }}
  erlang-cookie: {{ .Values.rabbitmq.erlangCookie | b64enc }}